# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'Mydaily_iOS' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

pod 'Moya', '~> 14.0'

  # Pods for Mydaily_iOS

end
